/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemManager;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.Restaurant.Restaurant;
import Business.Role.ManagerRole;
import Business.UserAccount.CustomerAccount;
import Business.UserAccount.EmployeeAccount;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.OrderRequest;
import UserInterface.Customer.CustomerProfileJPanel;
import UserInterface.Customer.OrderDetailJPanel;
import UserInterface.DeliveryMan.DeliveryManMainJPanel;
import UserInterface.Restaurant.RestaurantMainJPanel;
import java.awt.CardLayout;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author ranranhe
 */
public class DetailsJFrame extends javax.swing.JFrame {
    
    /**
     * Creates new form OrderDetailsJFrame
     */
    public DetailsJFrame(EcoSystem system, JPanel container, Enterprise en, UserAccount userAccount, JFrame frame, 
            OrderRequest order, Restaurant restaurant, String type) {
        initComponents();
        
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
        if (type.equalsIgnoreCase("Order")) {
            this.setSize(400, 500);
            this.setLocationRelativeTo(null);
            OrderDetailJPanel p = new OrderDetailJPanel(order, restaurant);
            this.container.add(p);
            CardLayout layout = (CardLayout) this.container.getLayout();
            layout.next(this.container);
            this.setVisible(true);
        }
        if (type.equalsIgnoreCase("Restaurant")) {
            this.setSize(950, 600);
            this.setLocationRelativeTo(null);
            RestaurantMainJPanel p = new RestaurantMainJPanel(system, container, en, userAccount, this, new ManagerRole());
            this.container.add(p);
            CardLayout layout = (CardLayout) this.container.getLayout();
            layout.next(this.container);
            this.setVisible(true);
        }
        if (type.equalsIgnoreCase("Customer")) {
            this.setSize(950, 600);
            this.setLocationRelativeTo(null);
            CustomerAccount ca = (CustomerAccount)userAccount;
            CustomerProfileJPanel p = new CustomerProfileJPanel(system, container, ca, this, new ManagerRole());
            this.container.add(p);
            CardLayout layout = (CardLayout) this.container.getLayout();
            layout.next(this.container);
            this.setVisible(true);
        }
        if (type.equalsIgnoreCase("DeliveryMan")) {
            this.setSize(950, 600);
            this.setLocationRelativeTo(null);
            EmployeeAccount ca = (EmployeeAccount)userAccount;
            DeliveryManMainJPanel p = new DeliveryManMainJPanel(system, container, en, ca, this, new ManagerRole());
            this.container.add(p);
            CardLayout layout = (CardLayout) this.container.getLayout();
            layout.next(this.container);
            this.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        container.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(OrderDetailsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(OrderDetailsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(OrderDetailsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(OrderDetailsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new OrderDetailsJFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel container;
    // End of variables declaration//GEN-END:variables
}
