/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Customer;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Restaurant.Restaurant;
import Business.UserAccount.CustomerAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author ranranhe
 */
public class RestaurantListJPanel extends javax.swing.JPanel {

    private EcoSystem system;
    private JPanel container;
    private CustomerAccount account;
    private Enterprise en;

    /**
     * Creates new form RestaurantListJPanel
     */
    public RestaurantListJPanel(EcoSystem system, JPanel container, CustomerAccount account, Enterprise en) {
        initComponents();
        this.system = system;
        this.container = container;
        this.account = account;
        this.en = en;

        populateTable(en.getRestaurantDirectory().getRestaurantList());
        areaLabel.setText(en.getCity());
        nameLabel.setText(account.getCustomer().getFirstName());
    }

    private void populateTable(ArrayList<Restaurant> list) {
        DefaultTableModel dtm = (DefaultTableModel) RestaurantTable.getModel();
        dtm.setRowCount(0);
        for (Restaurant res : list) {
            Object row[] = new Object[2];
            row[0] = res;
            row[1] = res.getCategory();
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        RestaurantTable = new javax.swing.JTable();
        detailPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        areaLabel = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        cartButton = new javax.swing.JButton();

        jScrollPane1.setPreferredSize(new java.awt.Dimension(200, 404));

        RestaurantTable.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        RestaurantTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Category"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        RestaurantTable.setPreferredSize(new java.awt.Dimension(200, 100));
        RestaurantTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RestaurantTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(RestaurantTable);

        detailPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        detailPanel.setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel1.setText("Welcome, ");

        nameLabel.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        nameLabel.setText("<Name>");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel3.setText("Restaurants in ");

        areaLabel.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        areaLabel.setText("<Area>");

        logoutButton.setText("Logout");

        cartButton.setText("Shopping Cart");
        cartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(detailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(areaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 267, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameLabel)
                .addGap(48, 48, 48)
                .addComponent(logoutButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cartButton)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(areaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoutButton)
                    .addComponent(cartButton))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                    .addComponent(detailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RestaurantTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RestaurantTableMouseClicked
        int index = RestaurantTable.getSelectedRow();
        TableModel model = RestaurantTable.getModel();
        Restaurant restaurant = (Restaurant) model.getValueAt(index, 0);

        if (index >= 0) {
            RestaurantDetailsJPanel panel = new RestaurantDetailsJPanel(this.system, restaurant, this.account);
            detailPanel.remove(this);
            detailPanel.add(panel);
            CardLayout layout = (CardLayout)this.detailPanel.getLayout();
            layout.next(detailPanel);
        }
    }//GEN-LAST:event_RestaurantTableMouseClicked

    private void cartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartButtonActionPerformed
        CartJFrame frame = new CartJFrame(this.system, this.account);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }//GEN-LAST:event_cartButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable RestaurantTable;
    private javax.swing.JLabel areaLabel;
    private javax.swing.JButton cartButton;
    private javax.swing.JPanel detailPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel nameLabel;
    // End of variables declaration//GEN-END:variables
}
